// import type { Metadata } from "next"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import LayoutRoot from "@/components/fragments/LayoutRoot"
import "./globals.css"

import { ThemeProvider } from "next-themes"

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`antialiased w-full h-screen `}>
				<NuqsAdapter>
					<LayoutRoot>{children}</LayoutRoot>
				</NuqsAdapter>
			</body>
		</html>
	)
}
