// import type { Metadata } from "next"
import LayoutRoot from "@/components/fragments/LayoutRoot"
import "./globals.css"

import { ThemeProvider } from "next-themes"

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="">
			<body className={`antialiased w-full h-screen `}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<LayoutRoot>{children}</LayoutRoot>
				</ThemeProvider>
			</body>
		</html>
	)
}
